### PR TITLE
Golang and Rust to Webassembly demo

### PR DESCRIPTION
**Pull request by jnyfah**

### CODE REVIEW

**Comment by nickvidal** [comment]
Looks great, @jnyfah! Would you mind just renaming file names / sidebar titles to simply "Rust" and "Golang" please?

**Comment by jnyfah** [comment]
Okay, would do that

**Comment by nickvidal** [comment]
I got this now. Almost there:

`Error: Image static/static/img/tutorial/golang-wasi.jpg used in docs/WebAssembly/Golang.md not found.
    at async Promise.all (index 0)
Error: Image static/static/img/tutorial/rust-wasi.jpg used in docs/WebAssembly/Rust.md not found.
    at async Promise.all (index 0)`

**Comment by nickvidal** [comment]
Hi Jennifer, still failing with image not found. Would you mind building locally before committing please?

**Pull request merged**
