### PR TITLE
docs: update C.md

### PR DESCRIPTION
**Pull request by aryankaushik-git**
## 🛠️ Fixes Issue
Due to the wrong name of the file, the wasicc command was not working.
but after the change in the name, it will work well.

## 👨‍💻 Changes proposed
There is a minor change in the file name, which will help to execute the wasicc command.

- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot from 2022-03-31 03-10-29

### CODE REVIEW

**Comment by aryankaushik-git** [comment]
Hi Nick Sir, Can you please help me to understand where exactly my pull request is making an error.

Regards

**Comment by nickvidal** [comment]
Hi @aryankaushik-git, thank you for this. All is fine, the only issue is that we are using conventional commits. If you could make this small change please, it will work:

https://enarx.dev/docs/Contributing/PRs#commit-messages

**Comment by aryankaushik-git** [comment]
@nickvidal sir, I'm working on it.

**Comment by Deepansharora27** [comment]
@aryankaushik-git This is not an error this is a typo mistake. 
You can name your source code file as per your convention and generate a output file which then can be converted to a WASM Binary

**Comment by aryankaushik-git** [comment]
@Deepansharora27  yeah you are right.
But when someone is just following the doc and copying as it is, can waste a lot of time. I personally while executing the code wasted a lot of time figuring out what was wrong, that's why I thought it need some correction.

**Review by aryankaushik-git — COMMENTED** [review]
Due to the wrong name of the file, the wasicc command was not working.
but after the change in the name, it will work well.

👨‍💻 Changes proposed
There is a minor change in the file name, which will help to execute the wasicc command.

[ x] My code follows the code style of this project.
[ x] This PR does not contain plagiarized content.
[ x] The title of my pull request is a short description of the requested changes.

**Comment by Deepansharora27** [comment]
@aryankaushik-git Though it's better to not copy and paste directly into your editor since that way you will not be able to retain the concept in a better way in your mind. But Anyways, good work fixing the typo. 
Also, you could have amended the commit message like this:
`docs: fix typo in C Docs`, since the WebAssembly guide has been already created and it is a typo fix

**Comment by aryankaushik-git** [comment]
@Deepansharora27 I understand the concern you mentioned and it is a genuine one but for every beginner, documentation matters a lot. That's why I thought there should be a change for this typo. But I really want to appreciate your effort in creating such guides for various languages.

**Comment by Deepansharora27** [comment]
> @Deepansharora27 I understand the concern you mentioned and it is a genuine one but for every beginner, documentation matters a lot. That's why I thought there should be a change for this typo. But I really want to appreciate your effort in creating such guides for various languages.

I Appreciate Your Efforts❤️

**Pull request closed without merging**
